spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug