spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
          init:
            schema: db/schema.sql
        slave_1:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
        slave_2:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug
beetlsql:
  dbStyle: org.beetl.sql.core.db.H2Style
  basePackage: com.baomidou.samples.beetl.dao