spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          init:
            schema: db/schema.sql
        tenant1_1:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        tenant1_2:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        tenant2_1:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          init:
            schema: db/schema.sql
        tenant2_2:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug