spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
    dynamic:
      p6spy: true
      lazy: true
      # 配置全局druid参数，请按需配置
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: 'select 1'
      datasource:
        master:
          username: sa
          password: "123456"
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
          init:
            schema: db/schema.sql
        slave_1:
          username: sa
          password: "123456"
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
          druid:
            initial-size: 6
        slave_2:
          username: sa
          password: "123456"
          url: jdbc:h2:mem:test
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug