spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          schema: classpath:db/schema.sql
        teacher:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        student:
          username: root
          password: henjiandan
          url: jdbc:mysql://localhost:3306/user_2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug